/**
 * mapping-store.ts — tier-aware dispatcher for mapping persistence
 * (capabilities_index §9: the persistence backend is a fork on `user.tier`).
 *
 * tier='free'  → IndexedDB locale in chiaro (§9.1)
 * tier='pro'   → POST/GET /recode/mappings/ cifrato AES-256-GCM (path esistente)
 *
 * The caller (active-mapping-context.tsx) deals in `MappingEntry[]` arrays;
 * this module hides the cipher / IDB plumbing behind a uniform API:
 *
 *   saveMapping(  { id, userId, tier, label, entries, masterKey } )  → string id
 *   loadMapping(  { id, tier, masterKey } )                          → SavedMapping
 *   listMappings( { userId, tier } )                                  → SavedMappingSummary[]
 *   deleteMapping({ id, tier })                                       → void
 *
 * For tier='pro', `masterKey` is mandatory (decrypt). For tier='free', it's
 * ignored. The dispatcher fails loudly when the contract is violated rather
 * than silently degrading to the wrong path.
 */

import {
  ApiError,
  deleteMapping as apiDeleteMapping,
  getMapping as apiGetMapping,
  listMappings as apiListMappings,
  saveMapping as apiSaveMapping,
} from '../api/client'
import {
  base64ToBytes,
  bytesToBase64,
  decryptMapping,
  encryptMapping,
} from '../api/crypto'
import type { MappingEntry } from '../types/engine'
import {
  IndexedDBQuotaError,
  deleteMapping as idbDelete,
  getMappingRecord,
  listMappingsForUser,
  putMapping,
  withDB,
  type MappingRecord,
} from './indexeddb-service'

export type Tier = 'free' | 'pro'

export type SavedMapping = {
  id: string
  label: string
  entries: MappingEntry[]
  createdAt: string
  updatedAt: string
}

export type SavedMappingSummary = {
  id: string
  label: string
  entriesCount: number
  createdAt: string
  updatedAt: string
}

export type SaveMappingInput = {
  /** UUID v4 — generated by the caller (active-mapping-context). */
  id: string
  userId: string
  tier: Tier
  label: string
  entries: MappingEntry[]
  /** Required for tier='pro' (encryption); unused for tier='free'. */
  masterKey?: CryptoKey | null
}

export type LoadMappingInput = {
  id: string
  tier: Tier
  /** Required for tier='pro'; unused for tier='free'. */
  masterKey?: CryptoKey | null
}

export type ListMappingsInput = {
  userId: string
  tier: Tier
}

export type DeleteMappingInput = {
  id: string
  tier: Tier
}

// ----- blob/entries round-trip helpers ----------------------------------
//
// Reused from active-mapping-context.tsx so the wire shape of the cloud
// blob and the structure of the local record stay in lockstep. Refactored
// here so both paths share the same serializer.

export function entriesToBlobMap(entries: MappingEntry[]): Map<string, string> {
  const out = new Map<string, string>()
  for (let i = 0; i < entries.length; i++) {
    const e = entries[i]!
    const key = `${i.toString().padStart(6, '0')}::${e.pseudonym}`
    const value = JSON.stringify({
      pseudonym: e.pseudonym,
      realValue: e.realValue,
      category: e.category,
      isFalsePositive: e.isFalsePositive === true,
    })
    out.set(key, value)
  }
  return out
}

export function blobMapToEntries(blob: Map<string, string>): MappingEntry[] {
  const entries: MappingEntry[] = []
  const keys = Array.from(blob.keys()).sort()
  for (const k of keys) {
    const raw = blob.get(k)
    if (!raw) continue
    try {
      const parsed = JSON.parse(raw)
      if (
        typeof parsed === 'object' &&
        parsed !== null &&
        typeof parsed.pseudonym === 'string' &&
        typeof parsed.realValue === 'string'
      ) {
        entries.push({
          pseudonym: parsed.pseudonym,
          realValue: parsed.realValue,
          category: typeof parsed.category === 'string' ? parsed.category : '',
          isFalsePositive: parsed.isFalsePositive === true,
        })
      }
    } catch {
      const pseudo = k.split('::').slice(1).join('::') || k
      entries.push({
        pseudonym: pseudo,
        realValue: raw,
        category: '',
        isFalsePositive: false,
      })
    }
  }
  return entries
}

// ----- dispatcher -------------------------------------------------------

function nowIso(): string {
  return new Date().toISOString()
}

/**
 * Save a mapping under the appropriate backend for the user's tier.
 * Returns the same `id` it received (the caller already generated the UUID,
 * either fresh for new saves or the existing id for re-saves).
 *
 * For tier='pro', re-saves use a delete-then-create cycle (matching the
 * pre-existing behaviour: the server's POST refuses duplicates with 409).
 * For tier='free', the IDB `put()` is naturally upsert via the keyPath.
 */
export async function saveMapping(input: SaveMappingInput): Promise<string> {
  if (input.tier === 'free') {
    const record: MappingRecord = {
      id: input.id,
      userId: input.userId,
      label: input.label,
      entries: input.entries,
      // We keep createdAt stable on overwrite by reading the previous record.
      // Cheap: same store, same id, one extra read.
      createdAt: nowIso(),
      updatedAt: nowIso(),
    }
    try {
      await withDB(async (db) => {
        const previous = await getMappingRecord(db, input.id)
        if (previous) record.createdAt = previous.createdAt
        await putMapping(db, record)
      })
    } catch (err) {
      if (err instanceof IndexedDBQuotaError) throw err
      throw err
    }
    return input.id
  }

  // tier === 'pro' — encrypt + POST.
  if (!input.masterKey) {
    throw new Error(
      'mapping-store.saveMapping: tier=pro richiede masterKey (decifratura assente).',
    )
  }
  const blobMap = entriesToBlobMap(input.entries)
  const cipher = await encryptMapping(blobMap, input.masterKey)
  const blob64 = bytesToBase64(cipher)
  // Idempotent overwrite: delete any prior row first (mirror of the
  // active-mapping-context behaviour pre-refactor).
  try {
    await apiDeleteMapping(input.id)
  } catch (err) {
    if (!(err instanceof ApiError && err.status === 404)) throw err
  }
  await apiSaveMapping({
    mapping_id: input.id,
    blob_base64: blob64,
    label: input.label,
    doc_type: 'txt',
  })
  return input.id
}

export async function loadMapping(input: LoadMappingInput): Promise<SavedMapping | null> {
  if (input.tier === 'free') {
    return await withDB(async (db) => {
      const r = await getMappingRecord(db, input.id)
      if (!r) return null
      return {
        id: r.id,
        label: r.label,
        entries: r.entries,
        createdAt: r.createdAt,
        updatedAt: r.updatedAt,
      }
    })
  }
  // tier === 'pro'
  if (!input.masterKey) {
    throw new Error(
      'mapping-store.loadMapping: tier=pro richiede masterKey (decifratura).',
    )
  }
  const payload = await apiGetMapping(input.id)
  const cipher = base64ToBytes(payload.blob)
  const blobMap = await decryptMapping(cipher, input.masterKey)
  const entries = blobMapToEntries(blobMap)
  return {
    id: payload.mapping_id,
    label: payload.label ?? '(senza etichetta)',
    entries,
    createdAt: payload.created_at,
    updatedAt: payload.last_accessed_at ?? payload.created_at,
  }
}

export async function listMappings(input: ListMappingsInput): Promise<SavedMappingSummary[]> {
  if (input.tier === 'free') {
    return await withDB(async (db) => {
      const records = await listMappingsForUser(db, input.userId)
      // Filtra il record aggregato sentinel (tier=free design 2026-05-19):
      // l'aggregato è un'astrazione di storage, non un mapping selezionabile
      // dall'utente — non deve mai apparire in nessuna lista UI.
      const aggId = aggregateRecordId(input.userId)
      return records
        .filter((r) => r.id !== aggId)
        .map((r) => ({
          id: r.id,
          label: r.label,
          entriesCount: r.entries.length,
          createdAt: r.createdAt,
          updatedAt: r.updatedAt,
        }))
    })
  }
  // tier === 'pro'
  const { mappings } = await apiListMappings()
  return mappings.map((m) => ({
    id: m.mapping_id,
    label: m.label ?? '(senza etichetta)',
    entriesCount: 0, // server doesn't surface entries-count without decrypt
    createdAt: m.created_at,
    updatedAt: m.last_accessed_at ?? m.created_at,
  }))
}

export async function deleteMappingById(input: DeleteMappingInput): Promise<void> {
  if (input.tier === 'free') {
    await withDB(async (db) => {
      await idbDelete(db, input.id)
    })
    return
  }
  await apiDeleteMapping(input.id)
}

// ----- aggregate mapping (tier=free, single record per userId) ----------
//
// Design ratificato 2026-05-19 (founder live test bug Recode IT zero-euro):
// tier=free NON è "lista multi-mapping con id" come tier=pro. È un SINGOLO
// record aggregato per browser, chiavato per userId, in cui vivono TUTTI i
// pseudonimi mai allocati per quell'utente. L'app lo carica all'avvio e
// seeda il PseudonymMapper engine così la continuità cross-documento è
// garantita: Mario Rossi → Tizio in Doc1 resta Tizio in Doc2.
//
// Implementazione: usiamo lo stesso object store `mappings` con un id
// deterministico `agg::<userId>` come unica key per il record aggregato.
// Coesiste con eventuali record legacy id-based ma per tier=free il flow
// applicativo passa SOLO da load/saveAggregateMapping.

/** Build the deterministic IDB key for the per-user aggregate record. */
export function aggregateRecordId(userId: string): string {
  return `agg::${userId}`
}

/**
 * Load the single aggregate mapping record for `userId`. Returns the
 * cumulative entry list (every name ever pseudonymized in this browser for
 * this user) or `[]` if no record yet exists.
 *
 * tier=free only. Pro users have a different topology (lista multi-mapping
 * cifrata server-side) e devono usare loadMapping(id).
 */
export async function loadAggregateMapping(userId: string): Promise<MappingEntry[]> {
  const id = aggregateRecordId(userId)
  return await withDB(async (db) => {
    const r = await getMappingRecord(db, id)
    return r ? r.entries : []
  })
}

/**
 * Save (upsert) the single aggregate mapping record for `userId`. The
 * caller passes the FULL merged entry list (the dispatcher does not merge —
 * pool merging lives in the engine / active-mapping-context). On overwrite
 * the original `createdAt` is preserved.
 */
export async function saveAggregateMapping(
  userId: string,
  entries: MappingEntry[],
): Promise<void> {
  const id = aggregateRecordId(userId)
  const now = nowIso()
  const record: MappingRecord = {
    id,
    userId,
    label: '__aggregate__', // sentinel; not surfaced in any list UI
    entries,
    createdAt: now,
    updatedAt: now,
  }
  try {
    await withDB(async (db) => {
      const previous = await getMappingRecord(db, id)
      if (previous) record.createdAt = previous.createdAt
      await putMapping(db, record)
    })
  } catch (err) {
    if (err instanceof IndexedDBQuotaError) throw err
    throw err
  }
}

export { IndexedDBQuotaError }
